### PR TITLE
Switch to coursier 1.1.0-M11-1 

### PR DESCRIPTION
**Pull request by alexarchambault**

### CODE REVIEW

**Comment by mdedetrich** [comment]
@alexarchambault Is there an ETA on this PR. it seems to be a blocker for getting sbt-coursier working with the latest releases of coursier

**Comment by alexarchambault** [comment]
@mdedetrich I was focusing on other stuff, but I'll make that work to unblock you. Either later today or first thing tomorrow.

**Comment by mdedetrich** [comment]
Thanks, its only in relation to https://github.com/coursier/coursier/pull/1057 so I can test that PR (in order to see if I am barking up the right tree)

**Comment by alexarchambault** [comment]
@mdedetrich sbt-coursier `1.1.0-M11` is out

**Pull request merged**
