### PR TITLE
Forward missingOk to forceFetch 

### PR DESCRIPTION
**Pull request by eed3si9n**
This is a continuation of #212 and #223
Ref coursier/coursier#1541
Ref sbt/sbt#4707
Ref sbt/sbt#5374
Ref sbt/sbt#5501

#212 fixed the resolve, but did not handle missing sources during fetch. This attempts to fix that.

### CODE REVIEW

**Comment by alexarchambault** [comment]
It seems the additional scripted test [is failing in sbt-lm-coursier on Travis CI](https://travis-ci.org/github/coursier/sbt-coursier/jobs/683866761#L710-L738):
```text
[info] [info] Loading settings for project update-sbt-classifiers2 from build.sbt ...
[info] [info] Set current project to update-sbt-classifiers2 (in build file:/tmp/sbt_6a56f7d1/update-sbt-classifiers2/)
[info] [error] lmcoursier.internal.shaded.coursier.error.FetchError$DownloadingArtifacts: Error fetching artifacts:
[info] [error] https://repo1.maven.org/maven2/org/webjars/npm/4.2.0/npm-4.2.0-sources.jar: not found: https://repo1.maven.org/maven2/org/webjars/npm/4.2.0/npm-4.2.0-sources.jar
[info] [error] 
[info] [error] 	at lmcoursier.internal.shaded.coursier.Artifacts$.$anonfun$fetchArtifacts$14(Artifacts.scala:302)
[info] [error] 	at lmcoursier.internal.shaded.coursier.util.Task$.$anonfun$flatMap$2(Task.scala:14)
[info] [error] 	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
[info] [error] 	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
[info] [error] 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[info] [error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[info] [error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[info] [error] 	at java.lang.Thread.run(Thread.java:748)
[info] [error] Caused by: lmcoursier.internal.shaded.coursier.cache.ArtifactError$NotFound: not found: https://repo1.maven.org/maven2/org/webjars/npm/4.2.0/npm-4.2.0-sources.jar
[info] [error] 	at lmcoursier.internal.shaded.coursier.cache.FileCache.$anonfun$download$12(FileCache.scala:244)
[info] [error] 	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:658)
[info] [error] 	at scala.util.Success.$anonfun$map$1(Try.scala:255)
[info] [error] 	at scala.util.Success.map(Try.scala:213)
[info] [error] 	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
[info] [error] 	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
[info] [error] 	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
[info] [error] 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[info] [error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[info] [error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[info] [error] 	at java.lang.Thread.run(Thread.java:748)
[info] [error] (updateSbtClassifiers) lmcoursier.internal.shaded.coursier.error.FetchError$DownloadingArtifacts: Error fetching artifacts:
[info] [error] https://repo1.maven.org/maven2/org/webjars/npm/4.2.0/npm-4.2.0-sources.jar: not found: https://repo1.maven.org/maven2/org/webjars/npm/4.2.0/npm-4.2.0-sources.jar
[info] [error] Total time: 3 s, completed May 7, 2020 5:47:50 PM
```

**Comment by eed3si9n** [comment]
`sbt-lm-coursier/scripted shared-2/update-sbt-classifiers2` works on my machine. Not sure why.

**Comment by alexarchambault** [comment]
> `sbt-lm-coursier/scripted shared-2/update-sbt-classifiers2` works on my machine. Not sure why.

Probably https://github.com/coursier/sbt-coursier/pull/223#issuecomment-628738127

**Comment by eed3si9n** [comment]
I'm closing this PR in favor of https://github.com/coursier/sbt-coursier/pull/232

**Comment by alexarchambault** [comment]
https://github.com/coursier/sbt-coursier/pull/232 doesn't take into account `missingOk` when fetching artifacts yet, I'm going to add it (or change its updateSbtClassifiers stuff for it).

**Pull request closed without merging**
