### PR TITLE
Forward classpathOrder into SbtUpdateReport

### PR DESCRIPTION
**Pull request by dwijnand**
Attempt at fixing coursier/coursier#1466

### CODE REVIEW

**Comment by dwijnand** [comment]
So your commit seemed to have fixed my "cp-order" test (🎉) but broken "shared-2 / scala-jars".  I haven't looked at it, but do you know why that might be?

**Comment by alexarchambault** [comment]
It seems the `scala-jars` test needed an update, it was relying on some possible stale assumptions about how sbt was handling the scala-library/reflect/compiler JARs. (That test checks that these are the same sbt itself uses when the user module uses the exact same scala version as sbt.)

**Comment by dwijnand** [comment]
Oh, right.  Causes by my 1.2.8 upgrade then.  Nice work.

**Comment by alexarchambault** [comment]
Merging, thanks @dwijnand!

**Pull request merged**
