### PR TITLE
Implement missingOk

### PR DESCRIPTION
**Pull request by eed3si9n**
Fixes https://github.com/coursier/coursier/issues/1541
Ref https://github.com/sbt/sbt/issues/4707
Ref https://github.com/sbt/sbt/issues/5374
Ref https://github.com/sbt/sbt/issues/5501
See also https://github.com/coursier/sbt-coursier/pull/204

This adds `missingOk` setting to `CoursierConfiguration`, forwarding the `missingOk` setting in `UpdateConfiguration` from LM API. lmcoursier _not_ respecting this setting is causing various issues on sbt side since the expected behavior of some plugins (including IntelliJ import feature) is that the source JARs missing would not fail the entire operation.
Ideally we should return a partially resolved graph (for example if one out of 20 depdencies are missing source JARs it's still useful), but for now I'm going to return an empty `UpdateReport`.

### CODE REVIEW

**Comment by OlegYch** [comment]
if this doesn't produce correct report (meaning intellij won't see any sources or even jars) then i'm afraid merging it will only obscure the issue

**Comment by hepin1989** [comment]
That's true, I can't import sbt sources in akka/akka even with the work aroud.

**Comment by eed3si9n** [comment]
While I was testing I saw stack trace that looks like this on sbt-coursier tests:

```
[info] [error] coursier.error.ResolutionError$CantDownloadModule: Error downloading org.webjars:npm:0.0.99
[info] [error]   Not found
[info] [error]   Not found
[info] [error]   not found: /Users/eed3si9n/.ivy2/local/org.webjars/npm/0.0.99/ivys/ivy.xml
[info] [error]   not found: https://repo1.maven.org/maven2/org/webjars/npm/0.0.99/npm-0.0.99.pom
[info] [error]   not found: https://repo.typesafe.com/typesafe/ivy-releases/org.webjars/npm/0.0.99/ivys/ivy.xml
[info] [error]   not found: https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.webjars/npm/0.0.99/ivys/ivy.xml
[info] [error] 	at coursier.Resolve$.$anonfun$validate$1(Resolve.scala:325)
[info] [error] 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:237)
[info] [error] 	at scala.collection.Iterator.foreach(Iterator.scala:941)
[info] [error] 	at scala.collection.Iterator.foreach$(Iterator.scala:941)
[info] [error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
[info] [error] 	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[info] [error] 	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[info] [error] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[info] [error] 	at scala.collection.TraversableLike.map(TraversableLike.scala:237)
[info] [error] 	at scala.collection.TraversableLike.map$(TraversableLike.scala:230)
[info] [error] 	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
[info] [error] 	at coursier.Resolve$.validate(Resolve.scala:323)
[info] [error] 	at coursier.Resolve.validate0$1(Resolve.scala:112)
[info] [error] 	at coursier.Resolve.$anonfun$ioWithConflicts0$4(Resolve.scala:156)
[info] [error] 	at coursier.util.Task$.$anonfun$flatMap$2(Task.scala:14)
[info] [error] 	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
[info] [error] 	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
[info] [error] 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[info] [error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[info] [error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[info] [error] 	at java.lang.Thread.run(Thread.java:748)
[info] [error] (coursierResolutions) coursier.error.ResolutionError$CantDownloadModule: Error downloading org.webjars:npm:0.0.99
```

So I guess if we want the partial graph, we need to pass in `missingOk` equivalent into `coursier.Resolve` to relax the validation - https://github.com/coursier/coursier/blob/master/modules/coursier/shared/src/main/scala/coursier/Resolve.scala /cc @alexarchambault

**Comment by alexarchambault** [comment]
Yes, I think we shouldn't simply discard resolutions if anything failed (as you hinted at, @eed3si9n). It's possible to keep partially failing resolutions, and attempt to fetch its artifacts and build an update report out of it. The `--force-fetch` option of the `fetch` command of the coursier CLI does it for example:
```bash
$ cs fetch com.chuusai::shapeless:2.3.3 org:name:ver --force-fetch
Error downloading org:name:ver
  not found: /Users/alexandre/.ivy2/local/org/name/ver/ivys/ivy.xml
  not found: https://repo1.maven.org/maven2/org/name/ver/name-ver.pom
/path/to/cache/v1/https/repo1.maven.org/maven2/com/chuusai/shapeless_2.13/2.3.3/shapeless_2.13-2.3.3.jar
/path/to/cache/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.0/scala-library-2.13.0.jar
```

Around [here](https://github.com/coursier/sbt-coursier/blob/e421e02c8d6877b9f665235cf137eceeec572587/modules/sbt-coursier/src/main/scala/coursier/sbtcoursier/ResolutionTasks.scala#L164), `err` is a [`coursier.error.ResolutionError`](https://github.com/coursier/coursier/blob/7dc458974ce0e88ae30f6a60242978a328a286ff/modules/coursier/shared/src/main/scala/coursier/error/ResolutionError.scala). `ResolutionError` has a `resolution` field, with the last state of the resolution. I guess we should just use it when `missingOk` is true.

Then [when we fetch artifacts](https://github.com/coursier/sbt-coursier/blob/e421e02c8d6877b9f665235cf137eceeec572587/modules/lm-coursier/src/main/scala/lmcoursier/internal/ArtifactsRun.scala#L14), I think errors are already handled correctly. Artifacts from Maven repositories are flagged as optional, so not-found errors are ignored. There's no special handling of artifacts errors in `--force-fetch` at least. If ever that was not enough, we may have to tweak [`coursier.Artifacts`](https://github.com/coursier/coursier/blob/master/modules/coursier/jvm/src/main/scala/coursier/Artifacts.scala) or [`coursier.error.FetchError`](https://github.com/coursier/coursier/blob/7dc458974ce0e88ae30f6a60242978a328a286ff/modules/coursier/jvm/src/main/scala/coursier/error/FetchError.scala) so that we can get partial results anyway.

**Comment by eed3si9n** [comment]
@alexarchambault Got around to recovering the partial resolution. Does ed2ed54 look ok?

**Comment by andreaTP** [comment]
Just to say, @eed3si9n thank you so much for your dedication, and for helping out everyone out there with your effort.
That's incredibly appreciated, and felt on a daily basis!!!

**Comment by eed3si9n** [comment]
@andreaTP Thanks Andrea :)

@alexarchambault Awesome.

**Comment by alexarchambault** [comment]
Will cut a release right after https://github.com/coursier/sbt-coursier/pull/222 is merged.

**Comment by alexarchambault** [comment]
FYI, I cut `2.0.0-RC6-4`, which includes this. Waiting for [Travis CI](https://travis-ci.org/github/coursier/sbt-coursier/builds/683506260) to release it.

**Pull request merged**
