### PR TITLE
Enable classpath ordering (w/ disable option)

### PR DESCRIPTION
**Pull request by dwijnand**
Refs coursier/coursier#1466

### CODE REVIEW

**Comment by alexarchambault** [comment]
@dwijnand Does this solve https://github.com/coursier/coursier/issues/1466 at the end? (Is our ordering the one expected by play-test?)

**Comment by dwijnand** [comment]
No idea.  I was just lazily changing the thing you suggested and hoping for the best...  I'll try to test it before January is finished...

**Comment by dwijnand** [comment]
Thanks for the publish.

**Comment by dwijnand** [comment]
Oh wait, that was https://github.com/coursier/coursier/releases/tag/v2.0.0-RC5-6.  Does that release include this change?

**Comment by dwijnand** [comment]
(Continuing in coursier/coursier#1466.)

**Pull request merged**
