### PR TITLE
Use dataclass-scalafix for code gen

### PR DESCRIPTION
**Pull request by eed3si9n**
This is a prepration step for Scala 3 support.
Instead of data-class, this uses
https://github.com/hamnis/dataclass-scalafix.

Since it cannot use `withX` method in the data class itself with this
approach, I created `syntax` package object to extend some methods to
the generated classes.

### CODE REVIEW

**Comment by alexarchambault** [comment]
Thanks @eed3si9n!

Doesn't this break IDE support somehow? (I'm fine merging even if that breaks this... While I'd be against it in coursier/coursier, sbt-coursier seems to be the right repo to experiment with that.)

About reviewing this, could you break the changes here in individual commits? Like "addressing deprecations", "using sbt slash syntax", "move methods to syntax object", "use scalafix to generate dataclasses", for example. That should make it easier to review things.

**Comment by eed3si9n** [comment]
> Doesn't this break IDE support somehow? (I'm fine merging even if that breaks this... While I'd be against it in coursier/coursier, sbt-coursier seems to be the right repo to experiment with that.)

Which part? `syntax.scala` moves some methods out of extension methods. IDEs can handle those ok. See checkLegacyCache():

SbtCoursierShared_scala

**Comment by eed3si9n** [comment]
> About reviewing this, could you break the changes here in individual commits? 

Sure. I can break them up a bit.

**Comment by alexarchambault** [comment]
> Which part? `syntax.scala` moves some methods out of extension methods. IDEs can handle those ok.

I'd expect go-to-definition to be borked or to bring to generated sources rather than the original `@data` annotated ones, both in the repo here and for dependees. (No big deal though…)

**Review by alexarchambault — APPROVED** [review]

**Comment by alexarchambault** [comment]
Thanks!

**Comment by eed3si9n** [comment]
Kudos @hamnis for dataclass-scalafix, and addressing issues as they popped up.

**Pull request merged**
