### PR TITLE
Scala 2.13 support

### PR DESCRIPTION
**Pull request by eed3si9n**

### CODE REVIEW

**Review by alexarchambault — APPROVED** [review]
Thanks @eed3si9n!

**Comment by alexarchambault** [comment]
@eed3si9n I assume you're trying to bump the Scala version in sbt?

**Comment by eed3si9n** [comment]
Yea. Laying out the groundwork for sbt 2.x.

**Comment by alexarchambault** [comment]
[This job](https://github.com/coursier/sbt-coursier/actions/runs/476194233) should push 2.13 artifacts for `2.0.8`.

**Pull request merged**
