### PR TITLE
Switch to coursier 2.0.0-RC3

### PR DESCRIPTION
**Pull request by alexarchambault**
~(Being published right now.)~

### CODE REVIEW

**Comment by alexarchambault** [comment]
CI error is legit… https://github.com/coursier/coursier/pull/1303 should help.

**Comment by eed3si9n** [comment]
https://github.com/coursier/sbt-coursier/pull/109 passed.

**Comment by alexarchambault** [comment]
> #109 passed.

Yeah, because @scala-steward is drunk ^^ (look at the diff)

**Comment by eed3si9n** [comment]
#110 (2.0.0-RC3-1) also passed.

**Pull request merged**
