### PR TITLE
Resolve license inheritence in update report

### PR DESCRIPTION
**Pull request by raboof**
In addition to the unit test, tested by running the scripted tests on the `use-update` branch of `sbt-license-report` at https://github.com/sbt/sbt-license-report/pull/123

Fixes https://github.com/coursier/coursier/issues/1790

### CODE REVIEW

**Comment by raboof** [comment]
AFAICS this should now be good to go

**Review by eed3si9n — APPROVED** [review]
Thanks!

**Comment by raboof** [comment]
I'd really like to see a release with this change in - anything I can do to help? :innocent:

**Comment by eed3si9n** [comment]
Thanks for the reminder. I can get one out soon.

**Pull request merged**
