### PR TITLE
test updateSbtClassifiers

### PR DESCRIPTION
**Pull request by OlegYch**
check if missingOk fixes updateSbtClassifiers

### CODE REVIEW

**Comment by eed3si9n** [comment]
I am not sure why, but `sbt-lm-coursier/scripted shared-2/update-sbt-classifiers2` works for me locally.

**Comment by OlegYch** [comment]
@eed3si9n currently it fails for me locally, but it is flaky
i'm guessing there is some bug in caching which makes this pass sometimes

**Comment by alexarchambault** [comment]
It seems one needs to remove `~/.ivy2/exclude_classifiers` prior to running the test, to make it fail. It's not cached on the CI, so the test fails there as expected.

This file is generated by sbt [around here](https://github.com/sbt/sbt/blob/f1370a25feb723e0da1d205b83eae93448595ca2/main/src/main/scala/sbt/internal/LibraryManagement.scala#L318), and it ignores `sbt.ivy.home` (so the scripted tests do look at `~/.ivy2/exclude_classifiers` too…).

**Comment by alexarchambault** [comment]
https://github.com/coursier/sbt-coursier/pull/232/commits/ce3620fe65f1d1dc0355794ae96ceb39b34cdd35 (in https://github.com/coursier/sbt-coursier/pull/232) makes the test pass, even with a clean / empty `~/.ivy2/exclude_classifiers`.

**Comment by OlegYch** [comment]
@alexarchambault awesome, thanks

**Pull request closed without merging**
